package api

import (
	"encoding/json"
	"errors"
	"net/http"
	"time"

	"github.com/Busness-app/kysignon-server/internal/auth"
	"github.com/Busness-app/kysignon-server/internal/crypto"
	"github.com/Busness-app/kysignon-server/internal/store"
	"github.com/google/uuid"
)

// StepUpTTL is how long a step-up grant stays valid. Long enough to scan a QR code and read
// a rotating code off an authenticator, short enough that it is not a second session token.
const StepUpTTL = 5 * time.Minute

// StepUpHeader carries the grant on the operation it authorizes.
const StepUpHeader = "X-KySignOn-StepUp"

var errStepUpRequired = errors.New("step-up authentication required")

type stepUpRequest struct {
	Password string `json:"password"`
	Code     string `json:"code"`
}

// RequestStepUp re-proves the account's own credentials and issues a short-lived, single-use
// grant bound to this user and session.
//
// Account-security changes cannot be gated on "is logged in" alone. A stolen session that
// cannot pass the victim's existing MFA could otherwise install attacker-controlled MFA and
// reissue recovery codes, and verifying a code generated by the attacker's own new secret
// proves nothing about the legitimate user.
func (h *AuthHandler) RequestStepUp(w http.ResponseWriter, r *http.Request) {
	user := GetUserFromContext(r.Context())
	sess := GetSessionFromContext(r.Context())
	if user == nil || sess == nil {
		http.Error(w, `{"error":"unauthorized"}`, http.StatusUnauthorized)
		return
	}

	var req stepUpRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.Password == "" {
		auth.DummyVerify(req.Password)
		http.Error(w, `{"error":"invalid_request","error_description":"Password is required"}`, http.StatusBadRequest)
		return
	}

	locked, err := h.store.IsAccountLocked(user.ID)
	if err != nil {
		http.Error(w, `{"error":"internal_error"}`, http.StatusInternalServerError)
		return
	}
	if locked {
		h.audit.Record("auth.step_up", user.ID, user.Username, user.ID, "user", h.middleware.ClientIP(r), r.UserAgent(), "denied",
			map[string]any{"reason": "account_locked"})
		http.Error(w, `{"error":"account_locked"}`, http.StatusTooManyRequests)
		return
	}

	ok, err := auth.VerifyPassword(req.Password, user.PasswordHash)
	if err != nil || !ok {
		_, _ = h.store.RecordFailedLogin(user.ID)
		h.audit.Record("auth.step_up", user.ID, user.Username, user.ID, "user", h.middleware.ClientIP(r), r.UserAgent(), "denied",
			map[string]any{"reason": "bad_password"})
		http.Error(w, `{"error":"invalid_credentials"}`, http.StatusUnauthorized)
		return
	}

	// A TOTP code is demanded in addition to the password so a session thief who also
	// phished the password still cannot replace the factor they cannot pass. This only
	// covers accounts with TOTP enrolled: passkeys are not in mfa_methods, so an account
	// whose sole second factor is a passkey (or a push device) currently gets a step-up
	// grant from the password alone. Tracked as a follow-up, not fixed here.
	methods, err := h.store.ListUserMFAMethods(user.ID)
	if err != nil {
		http.Error(w, `{"error":"internal_error"}`, http.StatusInternalServerError)
		return
	}
	if hasTOTP(methods) {
		if req.Code == "" {
			http.Error(w, `{"error":"mfa_required","error_description":"An existing authenticator code or recovery code is required"}`, http.StatusUnauthorized)
			return
		}
		verified, err := h.mfaEngine.VerifyUserTOTP(user.ID, req.Code)
		if err != nil {
			http.Error(w, `{"error":"internal_error"}`, http.StatusInternalServerError)
			return
		}
		if !verified {
			// A recovery code is the documented way in when the authenticator is gone.
			used, rerr := h.mfaEngine.VerifyAndConsumeRecoveryCode(user.ID, req.Code)
			if rerr != nil {
				http.Error(w, `{"error":"internal_error"}`, http.StatusInternalServerError)
				return
			}
			if !used {
				_, _ = h.store.RecordFailedLogin(user.ID)
				h.audit.Record("auth.step_up", user.ID, user.Username, user.ID, "user", h.middleware.ClientIP(r), r.UserAgent(), "denied",
					map[string]any{"reason": "bad_second_factor"})
				http.Error(w, `{"error":"invalid_code","error_description":"Code verification failed"}`, http.StatusUnauthorized)
				return
			}
		}
	}

	_ = h.store.ClearFailedLogins(user.ID)

	token, err := crypto.GenerateRandomHex(32)
	if err != nil {
		http.Error(w, `{"error":"internal_error"}`, http.StatusInternalServerError)
		return
	}
	expiresAt := time.Now().UTC().Add(StepUpTTL)
	if err := h.store.CreateStepUpToken(&store.StepUpToken{
		ID:        uuid.New().String(),
		UserID:    user.ID,
		SessionID: sess.ID,
		TokenHash: crypto.HashSHA256(token),
		ExpiresAt: expiresAt,
	}); err != nil {
		http.Error(w, `{"error":"internal_error"}`, http.StatusInternalServerError)
		return
	}

	h.audit.Record("auth.step_up", user.ID, user.Username, user.ID, "user", h.middleware.ClientIP(r), r.UserAgent(), "success", nil)

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]any{
		"stepUpToken": token,
		"expiresAt":   expiresAt,
	})
}

func hasTOTP(methods []store.MFAMethod) bool {
	for _, m := range methods {
		if m.MethodType == "totp" {
			return true
		}
	}
	return false
}

// requireStepUp checks the grant carried on this request without spending it. Use for
// read-only steps that should fail early rather than after the operator has done work.
func requireStepUp(s *store.Store, r *http.Request) error {
	user := GetUserFromContext(r.Context())
	sess := GetSessionFromContext(r.Context())
	raw := r.Header.Get(StepUpHeader)
	if user == nil || sess == nil || raw == "" {
		return errStepUpRequired
	}
	valid, err := s.HasValidStepUpToken(crypto.HashSHA256(raw), user.ID, sess.ID)
	if err != nil {
		return err
	}
	if !valid {
		return errStepUpRequired
	}
	return nil
}

// consumeStepUp spends the grant carried on this request. Every mutating account-security
// operation calls this, so one re-authentication authorizes exactly one change.
func consumeStepUp(s *store.Store, r *http.Request) error {
	user := GetUserFromContext(r.Context())
	sess := GetSessionFromContext(r.Context())
	raw := r.Header.Get(StepUpHeader)
	if user == nil || sess == nil || raw == "" {
		return errStepUpRequired
	}
	spent, err := s.ConsumeStepUpToken(crypto.HashSHA256(raw), user.ID, sess.ID)
	if err != nil {
		return err
	}
	if !spent {
		return errStepUpRequired
	}
	return nil
}

// writeStepUpError distinguishes "you need to re-authenticate" from a server fault so the UI
// can prompt instead of showing a dead end.
func writeStepUpError(w http.ResponseWriter, err error) {
	if errors.Is(err, errStepUpRequired) {
		http.Error(w, `{"error":"step_up_required","error_description":"Re-enter your password to change account security settings"}`, http.StatusForbidden)
		return
	}
	http.Error(w, `{"error":"internal_error"}`, http.StatusInternalServerError)
}
